// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import ClientConditionalSidebar from "@/components/ClientConditionalSidebar";
// import UserProvider from "@/context/UserContext";
const inter = Inter({ subsets: ["latin"] });
import { UserProvider } from "@/context/UserContext";
export const metadata = {
  title: "RedMath",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
        <div className="flex flex-row">
            {children}
        </div>
        </UserProvider>
      </body>
    </html>
  );
}
